### ISSUE TITLE
SSL enable in reddit breaks Diode

### ISSUE THREAD

**Issue by AfterSpencer** [zagaberoo/diode#39]
I am unable to see my subreddits in diode when SSL is on for my account.

**Comment by AfterSpencer** [comment]
Diode doesn't support https being forced. On June 29 reddit will be going to https only. [source](https://np.reddit.com/r/redditdev/comments/39zje0/reddit_will_soon_only_be_available_over_https/)

I wish I was a developer so I could fix it myself. (I looked into it and it is beyond my skill :( )

**Comment by zagaberoo** [comment]
I'll have to keep tabs on that thread.  If reddit is going to force everyone over HTTPS it'll screw a number of people over, but it would simplify my life quite a bit.  I could just do the quick and dirty solution of changing Diode over to 100% HTTPS with no configuration options for users and it wouldn't be my fault that people who can't use HTTPS are shut out.

Don't fret about not being a developer.  If people didn't remind me about stuff like this it would never get done, so thank you!

Someday, it's not clear when, [this](https://www.reddit.com/r/redditdev/comments/2ujhkr/important_api_licensing_terms_clarified/) thread will come to fruition and I'll have to move to OAuth which will entail using HTTPS as well.

One way or another this will have to get fixed eventually.

**Comment by zagaberoo** [comment]
Diode now always uses HTTPS, so this bug is effectively obsolete!
