### ISSUE TITLE
can't open links

### ISSUE THREAD

**Issue by algazarra** [zagaberoo/diode#42]
I can't open links. I also tried copying to my browser, but couldn't find out how to.

**Comment by zagaberoo** [comment]
I can't reproduce; could you be more specific?  Perhaps a screenshot?

**Comment by algazarra** [comment]
@zagaberoo, it's working now. Anyway, after clicking on a link you get links/reply pannel, I'd press link and a new pannel would appear and after that I wasn't able to continue. I'll report if i happens again.
