### ISSUE TITLE
Add share option to internal browser overflow menu

### ISSUE THREAD

**Issue by zagaberoo** [zagaberoo/diode#53]
It's pretty common to want to share a link while you're browsing it, so it makes sense to add share to the internal browser's overflow menu.

**Comment by mxa** [comment]
Or even before you open the internal browser, for example long press on the arrow for the content. That way you don't have to load the content just to copy the link.

**Comment by zagaberoo** [comment]
If you long click on the title rather than the arrow, share is already an option.  Is that what you're looking for?

**Comment by mxa** [comment]
![images duckduckgo com](https://cloud.githubusercontent.com/assets/1220707/9489060/2d29ce20-4c19-11e5-8d8b-5c24e7f752cf.jpeg)

**Comment by mxa** [comment]
Okay,  but what about if I want to share a permanent link to the discussion on reddit? Is there some other trick I've missed?

**Comment by zagaberoo** [comment]
A share comments option is a totally reasonable request; feel free to open a ticket for it.

**Comment by jolteony** [comment]
To be clear, this means to be able to share any page you are on after navigating away from the original link, and not just the original link?

**Comment by zagaberoo** [comment]
I think this is is solved by your recent PR, jolteony.

This really should have been closed a while back since this specific ticket is for share link, which already existed.  The issue your PR just closed spawned from the discussion here.
