### ISSUE TITLE
Handle locked threads

### ISSUE THREAD

**Issue by Protuhj** [zagaberoo/diode#65]
First obvious way is to disable the 'reply' button for locked threads.

I'm wondering about the visual indication though. 

I've got a version showing the lock emoji (🔒) next to the comments count at the top, but I don't think it's necessarily big enough.

I was thinking that it could have a similar banner like the "viewing a single comment's context" banner. 

Any thoughts?

**Comment by zagaberoo** [comment]
I think a banner is the best option.

That would be cleaner than toast for archived objects too!

**Comment by Protuhj** [comment]
So, in the case of Archived and Locked, you think archived should take precedence?

**Comment by Protuhj** [comment]
The branch I made has archived supersede locked.

**Comment by zagaberoo** [comment]
Archived over locked sounds logical to me.

**Comment by zagaberoo** [comment]
Fixed by PR #66
