### ISSUE TITLE
Something is causing an Activity crash with the new archived/locked code

### ISSUE THREAD

**Issue by Protuhj** [zagaberoo/diode#67]
I've seen a couple times now that the app will crash if I go to a locked/archived thread, then allow the app to get written to disk ( I think ), and then when I open it up, and try to go back to the thread listing, the Activity crashes.

I'm pretty sure this is something I've introduced, I just need to catch the error occurring when I have the Android monitor open.

**Comment by zagaberoo** [comment]
Thanks for the update; I'll hold off the release.

Let me know if working with the monitor is cumbersome; I can always set up the current build as a beta so you can opt-in and then submit crashes directly to the google play console.

**Comment by Protuhj** [comment]
I think I've got the workflow that can reproduce the crash, I just don't know how long I need to let the app sleep before the error occurs.

If you've got a guaranteed way to test the lifecycle functionality, I could use some tips. (I'm not an Android dev professionally).

**Comment by zagaberoo** [comment]
I've always just been an Android hobbyist too, and debugging/testing is definitely my worst suit.

**Comment by Protuhj** [comment]
I tried last night to reproduce the issue with no luck.

I may add an uncaught exception handler to my version to see if I can catch the error without babysitting the app.

**Comment by Protuhj** [comment]
That line I referenced has a bug. 

I don't understand how to exercise that code.

**Comment by zagaberoo** [comment]
That's definitely it!  WriteToParcel is used any time something needs to be serialized, be it to be packed into an inter-app Intent, or when being written out to disk.

**Comment by zagaberoo** [comment]
No idea, sorry to say.

**Comment by Protuhj** [comment]
For posterity: 
Okay -- to reliably test the Activity lifecycle, you can go into developer options (On your phone), and at the bottom, you can check "Don't keep activities". Once the Activity is written to a Parcel, attempting to reload the activity again, will load from the parcel.

I verified that when I had 13 in the array instead of 15, it crashed when I tried to go back, like I had experienced before.

**Comment by Protuhj** [comment]
My commit should have fixed this issue if you want to close it.
