### ISSUE TITLE
After latest update, app gets in a state where you can't get back to the front page

### ISSUE THREAD

**Issue by Protuhj** [zagaberoo/diode#84]
Hitting back when viewing comments, the app got to where I couldn't hit back to go back to the front page, which then meant I couldn't exit the app normally.

**Comment by Protuhj** [comment]
I believe this commit: https://github.com/zagaberoo/diode/commit/7813c6b35a53fab37d9e9d9e1e3e829d7ffebbea broke it.

**Comment by zagaberoo** [comment]
Fixed by reverting the feature for now.
